<a href="https://colab.research.google.com/github/SamDavies114/pyTorchDeepLearnIntro/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
import numpy as np

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [7]:
#addition
tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [9]:
#addition longhand
torch.add(tensor_a, tensor_b)


tensor([ 6,  8, 10, 12])

In [11]:
#sub
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [14]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [16]:
#mult
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [18]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [20]:
#div
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [22]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [24]:
#mod
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [26]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [28]:
#exp
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [30]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [34]:
#reassignemnt
tensor_a += tensor_b
tensor_a

tensor([21, 26, 31, 36])

In [36]:
tensor_a.add_(tensor_b)

tensor([31, 38, 45, 52])