<a href="https://colab.research.google.com/github/SamDavies114/pyTorchDeepLearnIntro/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.37029832, 0.44922804, 0.62926073, 0.43814676],
       [0.3806081 , 0.53700466, 0.02727775, 0.5794798 ],
       [0.54045704, 0.45742196, 0.97936952, 0.9854686 ]])

In [7]:
np1.dtype

dtype('float64')

In [9]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.2569, 0.2400, 0.3255, 0.7176],
        [0.8185, 0.8932, 0.3401, 0.3609],
        [0.5981, 0.4105, 0.4436, 0.3858]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
##numpy array to tensor
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3703, 0.4492, 0.6293, 0.4381],
        [0.3806, 0.5370, 0.0273, 0.5795],
        [0.5405, 0.4574, 0.9794, 0.9855]], dtype=torch.float64)